#!/usr/bin/env php
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
//BE SURE register_argc_argv = ON
define('_STATE_', 'console');

include(__DIR__ . '/console/system/ConsoleApplication.php');
$application = new \console\system\ConsoleApplication();
$output = $application->start();
?>
